/**
 * Scene-module codegen (lottie-import.md §1 output format): the importer
 * emits a generated TypeScript scene module — readable constructor calls plus
 * the inline Timeline document — consumable by `gs render` and the studio.
 */

import type { LottieImportResult, NodeSpec } from './spec.js';

const CTOR: Record<NodeSpec['kind'], string> = {
  group: 'Group',
  path: 'Path',
  rect: 'Rect',
  image: 'ImageNode',
  text: 'Text',
};

function lit(value: unknown, indent: string): string {
  return JSON.stringify(value, null, 2)
    .split('\n')
    .join(`\n${indent}`);
}

function emitNode(spec: NodeSpec, indent: string): string {
  const inner = `${indent}  `;
  const props: string[] = [`id: ${JSON.stringify(spec.id)}`];
  if (spec.position) props.push(`position: ${JSON.stringify(spec.position)}`);
  if (spec.rotation !== undefined) props.push(`rotation: ${spec.rotation}`);
  if (spec.scale) props.push(`scale: ${JSON.stringify(spec.scale)}`);
  if (spec.opacity !== undefined) props.push(`opacity: ${spec.opacity}`);
  if (spec.zIndex !== undefined) props.push(`zIndex: ${spec.zIndex}`);
  switch (spec.kind) {
    case 'group':
      if (spec.children.length > 0) {
        const children = spec.children.map((c) => `${inner}  ${emitNode(c, `${inner}  `)},`).join('\n');
        props.push(`children: [\n${children}\n${inner}]`);
      }
      break;
    case 'path':
      props.push(`data: ${lit(spec.data, inner)} as PathValue`);
      if (spec.fill !== undefined) props.push(`fill: ${JSON.stringify(spec.fill)}`);
      if (spec.stroke !== undefined) props.push(`stroke: ${JSON.stringify(spec.stroke)}`);
      if (spec.strokeWidth !== undefined) props.push(`strokeWidth: ${spec.strokeWidth}`);
      break;
    case 'rect':
      props.push(`width: ${spec.width}`, `height: ${spec.height}`);
      if (spec.fill !== undefined) props.push(`fill: ${JSON.stringify(spec.fill)}`);
      break;
    case 'image':
      props.push(`assetId: ${JSON.stringify(spec.assetId)}`, `width: ${spec.width}`, `height: ${spec.height}`);
      break;
    case 'text':
      props.push(
        `text: ${JSON.stringify(spec.text)}`,
        `fill: ${JSON.stringify(spec.fill)}`,
        `fontSize: ${spec.fontSize}`,
        `fontFamily: ${JSON.stringify(spec.fontFamily)}`,
      );
      if (spec.fontWeight !== undefined) props.push(`fontWeight: ${spec.fontWeight}`);
      if (spec.fontStyle !== undefined) props.push(`fontStyle: ${JSON.stringify(spec.fontStyle)}`);
      if (spec.align !== undefined) props.push(`align: ${JSON.stringify(spec.align)}`);
      if (spec.letterSpacing !== undefined) props.push(`letterSpacing: ${spec.letterSpacing}`);
      if (spec.lineHeight !== undefined) props.push(`lineHeight: ${spec.lineHeight}`);
      break;
  }
  return `new ${CTOR[spec.kind]}({\n${props.map((p) => `${inner}${p},`).join('\n')}\n${indent}})`;
}

export interface CodegenOptions {
  /** Provenance line, e.g. the source filename. */
  source?: string;
}

export function generateSceneModule(result: LottieImportResult, opts: CodegenOptions = {}): string {
  const usedKinds = new Set<NodeSpec['kind']>();
  const visit = (s: NodeSpec): void => {
    usedKinds.add(s.kind);
    if (s.kind === 'group') s.children.forEach(visit);
  };
  result.nodes.forEach(visit);
  const ctors = [...usedKinds].map((k) => CTOR[k]).sort();
  const usesPath = usedKinds.has('path');

  const children = result.nodes.map((n) => `      ${emitNode(n, '      ')},`).join('\n');
  const header = `// Generated by gs import${opts.source ? ` from ${opts.source}` : ''} (@glissade/lottie).`;
  const warnings = result.warnings.length
    ? `\n// Import warnings:\n${result.warnings.map((w) => `//   ${w}`).join('\n')}`
    : '';

  return `${header}${warnings}
import { ${ctors.join(', ')}, createScene, type SceneModule } from '@glissade/scene';
import type { ${usesPath ? 'PathValue, ' : ''}Timeline } from '@glissade/core';

export const timeline = ${lit(result.timeline, '')} as unknown as Timeline;

export default {
  createScene: () =>
    createScene({
      size: ${JSON.stringify(result.size)},
      children: [
${children}
      ],
    }),
  timeline,
} satisfies SceneModule;
`;
}
