/**
 * `gs describe --lint` + `gs types --global` (0.47) — the CLI commands end-to-end
 * (built dist/cli.js): the drift-lint exits 0 on the clean live manifest, and the
 * ambient-d.ts generator + its `--global --check` staleness gate work like `gs types`.
 */

import { spawnSync } from 'node:child_process';
import { appendFileSync, existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, describe, expect, it } from 'vitest';

const CLI = fileURLToPath(new URL('../dist/cli.js', import.meta.url));
const dir = mkdtempSync(join(tmpdir(), 'gs-ground-truth-'));
afterAll(() => rmSync(dir, { recursive: true, force: true }));
const gs = (...args: string[]) => spawnSync(process.execPath, [CLI, ...args], { encoding: 'utf8' });

describe.runIf(existsSync(CLI))('gs describe --lint (built CLI)', () => {
  it('exits 0 and reports OK on the clean live manifest', () => {
    const r = gs('describe', '--lint');
    expect(r.status).toBe(0);
    expect(r.stderr).toMatch(/gs describe --lint: OK/);
    // the two browser-only snapshot helpers can't be imported headlessly → reported skipped
    expect(r.stderr).toMatch(/browser-only helper/);
  });
});

describe.runIf(existsSync(CLI))('gs types --global (built CLI)', () => {
  const out = join(dir, 'glissade.d.ts');

  it('emits a self-contained ambient window.glissade .d.ts', () => {
    const r = gs('types', '--global', '--out', out);
    expect(r.status).toBe(0);
    const dts = readFileSync(out, 'utf8');
    expect(dts).toContain('declare global {');
    expect(dts).toContain('glissade: GlissadeGlobal;');
    expect(dts).toContain('"Rect": new (props?: GsRectProps) => GsNode;');
    expect(dts).toMatch(/GENERATED by `gs types --global`/);
  });

  it('--iife is an alias of --global', () => {
    const alias = join(dir, 'alias.d.ts');
    expect(gs('types', '--iife', '--out', alias).status).toBe(0);
    expect(readFileSync(alias, 'utf8')).toBe(readFileSync(out, 'utf8'));
  });

  it('--global --check passes (exit 0) when the committed file is up to date', () => {
    gs('types', '--global', '--out', out);
    expect(gs('types', '--global', '--out', out, '--check').status).toBe(0);
  });

  it('--global --check FAILS (exit 1) when the committed file is stale', () => {
    gs('types', '--global', '--out', out);
    appendFileSync(out, '// drift\n');
    const r = gs('types', '--global', '--out', out, '--check');
    expect(r.status).toBe(1);
    expect(r.stderr).toMatch(/STALE/);
  });

  it('--global --check without --out fails loud', () => {
    expect(gs('types', '--global', '--check').status).not.toBe(0);
  });
});
