/**
 * gs types (0.44) — the CLI command end-to-end (built dist/cli.js): generate a typed
 * track() SDK from the LIVE describe() manifest, and the --check staleness gate.
 */

import { spawnSync } from 'node:child_process';
import { appendFileSync, existsSync, readFileSync, rmSync, mkdtempSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, describe, expect, it } from 'vitest';

const CLI = fileURLToPath(new URL('../dist/cli.js', import.meta.url));
const dir = mkdtempSync(join(tmpdir(), 'gs-types-'));
afterAll(() => rmSync(dir, { recursive: true, force: true }));
const gs = (...args: string[]) => spawnSync(process.execPath, [CLI, 'types', ...args], { encoding: 'utf8' });

describe.runIf(existsSync(CLI))('gs types (built CLI)', () => {
  const out = join(dir, 'glissade-targets.ts');

  it('generates a typed track() SDK from the live describe() manifest', () => {
    const r = gs('--out', out);
    expect(r.status).toBe(0);
    const src = readFileSync(out, 'utf8');
    expect(src).toMatch(/export type KnownTrackPath =/);
    expect(src).toContain("| 'opacity'"); // a real animatable path from the taxonomy
    expect(src).toContain('export const track = _track as'); // the type-narrowed re-export
    expect(src).toContain("import { track as _track"); // runtime is core's track
    expect(src).toMatch(/GENERATED by `gs types`/);
  });

  it('--check passes (exit 0) when the committed file is up to date', () => {
    gs('--out', out);
    expect(gs('--out', out, '--check').status).toBe(0);
  });

  it('--check FAILS (exit 1) when the committed file is stale', () => {
    gs('--out', out);
    appendFileSync(out, '// drift\n');
    const r = gs('--out', out, '--check');
    expect(r.status).toBe(1);
    expect(r.stderr).toMatch(/STALE/);
  });

  it('--check without --out fails loud', () => {
    expect(gs('--check').status).not.toBe(0);
  });
});
