/**
 * `gs types` (0.44) — the typed SDK generator. Codegen a `.ts` from the `describe()`
 * ApiManifest so that `track('<node>/<path>', type, keys)` becomes TYPE-CHECKED:
 * only a REGISTERED animatable prop path typechecks, and its value type is inferred
 * per path — so a typo'd path (`opasity`) or a wrong value-type arg (`'color'` on a
 * `number` prop) is a COMPILE error, not a runtime `UnboundTargetError` / silent NaN.
 * Closes the "read the d.ts, don't guess" loop for AI/agent authorship.
 *
 * PURE codegen: manifest → source string. The generator is offline (no `evaluate()`),
 * zero-runtime (the output is types + a re-typed re-export of the real `track`), and
 * lives in `cli` — off every render/embed path. Modelled on `scripts/gen-api-docs.mjs`.
 *
 * SCOPE (honest): the manifest is INSTANCE-FREE — its `target` is the template
 * `'<id>/<path>'` — so this types the prop-PATH + value-type half. Verifying that the
 * `<id>` is a real node in a specific scene needs a per-scene introspection pass the
 * manifest doesn't carry (a follow-up); a bad node id still fails loud at bind time.
 */

import type { ApiManifest } from '@glissade/scene/describe';

/** value-type id → the TS type its keyframes carry. Unmapped ids fall back to `unknown`. */
const TS_VALUE_TYPE: Record<string, string> = {
  number: 'number',
  vec2: 'readonly [number, number]',
  'vec2-arc': 'readonly [number, number]',
  color: 'string',
  string: 'string',
  boolean: 'boolean',
  paint: 'Paint',
  fontAxes: 'FontAxes',
  path: 'PathValue',
};
/** core types the generated file must import when a mapped value type references them. */
const CORE_TYPE_IMPORTS: Record<string, string> = { paint: 'Paint', fontAxes: 'FontAxes', path: 'PathValue' };

/** One animatable target path + the value-type id it accepts. */
export interface TargetInfo {
  readonly path: string;
  readonly valueType: string;
}

/**
 * Collect every animatable prop path across the manifest's node taxonomy (+ the
 * component surface is construction-only, so excluded). Deduped by path; the FIRST
 * value type wins and a differing later one is reported in `conflicts` (base targets
 * are uniform — a conflict is a taxonomy smell worth surfacing, not silently picking).
 */
export function collectTargets(manifest: ApiManifest): { targets: TargetInfo[]; conflicts: string[] } {
  const byPath = new Map<string, string>();
  const conflicts: string[] = [];
  for (const node of Object.values(manifest.nodes)) {
    for (const [path, prop] of Object.entries(node.props)) {
      if (!prop.animatable || prop.target === undefined) continue;
      const existing = byPath.get(path);
      if (existing === undefined) byPath.set(path, prop.type);
      else if (existing !== prop.type) conflicts.push(`${path}: ${existing} vs ${prop.type}`);
    }
  }
  const targets = [...byPath.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([path, valueType]) => ({ path, valueType }));
  return { targets, conflicts };
}

const tsValueOf = (valueType: string): string => TS_VALUE_TYPE[valueType] ?? 'unknown';

/**
 * Generate the typed-SDK source (a `.ts` module). Emits a `KnownTrackPath` union, a
 * `TrackTarget` template (`` `${string}/${KnownTrackPath}` ``), per-path `TypeIdOf` /
 * `ValueOf` conditional maps, and a re-typed `track` re-export whose runtime IS
 * `@glissade/core`'s `track` (only the types are narrowed). Deterministic: paths are
 * sorted, so the same manifest → byte-identical output (drift-guardable with `--check`).
 */
export function generateTypedSdk(manifest: ApiManifest): string {
  const { targets, conflicts } = collectTargets(manifest);
  const usedCoreTypes = [...new Set(targets.map((t) => CORE_TYPE_IMPORTS[t.valueType]).filter((n): n is string => n !== undefined))].sort();

  const L: string[] = [];
  L.push(`// GENERATED by \`gs types\` from the describe() API manifest v${manifest.version} — DO NOT EDIT.`);
  L.push('// Regenerate after a glissade upgrade (or when you add a defineComponent target):');
  L.push('//   gs types --out glissade-targets.ts');
  L.push('// Then import `track` from here instead of @glissade/core to type-check your targets.');
  if (conflicts.length) L.push(`// NOTE: ${conflicts.length} path(s) carry >1 value type across nodes: ${conflicts.join(', ')}`);
  L.push('');
  L.push(`import { track as _track, type Track, type Key } from '@glissade/core';`);
  if (usedCoreTypes.length) L.push(`import type { ${usedCoreTypes.join(', ')} } from '@glissade/core';`);
  L.push('');

  L.push('/** Every animatable prop path in the describe() taxonomy — a typo\'d path is a type error. */');
  L.push(`export type KnownTrackPath =`);
  for (const t of targets) L.push(`  | '${t.path}'`);
  L.push(`  ;`);
  L.push('');
  L.push('/** A track target: any node id + a KNOWN animatable path. */');
  L.push('export type TrackTarget = `${string}/${KnownTrackPath}`;');
  L.push('');

  L.push('/** The value-type id each path expects (a wrong `type` arg is a type error). */');
  L.push('type TypeIdOf<P extends TrackTarget> =');
  for (const t of targets) L.push(`  P extends \`\${string}/${t.path}\` ? '${t.valueType}' :`);
  L.push('  never;');
  L.push('');
  L.push('/** The value each path animates (the keyframe value type). */');
  L.push('type ValueOf<P extends TrackTarget> =');
  for (const t of targets) L.push(`  P extends \`\${string}/${t.path}\` ? ${tsValueOf(t.valueType)} :`);
  L.push('  never;');
  L.push('');

  L.push('/**');
  L.push(' * Type-checked `track` — only a KNOWN path + its correct value type compile.');
  L.push(' * Runtime is `@glissade/core`\'s `track` verbatim (only the types are narrowed).');
  L.push(' */');
  L.push('export const track = _track as <P extends TrackTarget>(');
  L.push('  target: P,');
  L.push('  type: TypeIdOf<P>,');
  L.push('  keys: Key<ValueOf<P>>[],');
  L.push('  opts?: { editable?: boolean },');
  L.push(') => Track<ValueOf<P>>;');
  L.push('');
  return L.join('\n');
}
