/**
 * `gs types` (0.44) — the typed SDK generator. Codegen a `.ts` from the `describe()`
 * ApiManifest so that `track('<node>/<path>', type, keys)` becomes TYPE-CHECKED:
 * only a REGISTERED animatable prop path typechecks, and its value type is inferred
 * per path — so a typo'd path (`opasity`) or a wrong value-type arg (`'color'` on a
 * `number` prop) is a COMPILE error, not a runtime `UnboundTargetError` / silent NaN.
 * Closes the "read the d.ts, don't guess" loop for AI/agent authorship.
 *
 * PURE codegen: manifest → source string. The generator is offline (no `evaluate()`),
 * zero-runtime (the output is types + a re-typed re-export of the real `track`), and
 * lives in `cli` — off every render/embed path. Modelled on `scripts/gen-api-docs.mjs`.
 *
 * SCOPE (honest): the manifest is INSTANCE-FREE — its `target` is the template
 * `'<id>/<path>'` — so this types the prop-PATH + value-type half. Verifying that the
 * `<id>` is a real node in a specific scene needs a per-scene introspection pass the
 * manifest doesn't carry (a follow-up); a bad node id still fails loud at bind time.
 */

import type { ApiManifest, SurfaceEntry } from '@glissade/scene/describe';

/** value-type id → the TS type its keyframes carry. Unmapped ids fall back to `unknown`. */
const TS_VALUE_TYPE: Record<string, string> = {
  number: 'number',
  vec2: 'readonly [number, number]',
  'vec2-arc': 'readonly [number, number]',
  color: 'string',
  string: 'string',
  boolean: 'boolean',
  paint: 'Paint',
  fontAxes: 'FontAxes',
  path: 'PathValue',
};
/** core types the generated file must import when a mapped value type references them. */
const CORE_TYPE_IMPORTS: Record<string, string> = { paint: 'Paint', fontAxes: 'FontAxes', path: 'PathValue' };

/** One animatable target path + the value-type id(s) it accepts (a UNION for a
 *  polymorphic prop like `fill: color|paint`, or a path that differs across nodes). */
export interface TargetInfo {
  readonly path: string;
  readonly valueTypes: readonly string[];
}

/**
 * Collect every animatable prop path across the manifest's node taxonomy (component
 * props are construction-only → excluded). Value types are UNIONED per path — the
 * manifest encodes a polymorphic prop as a pipe-joined id (`'color|paint'`), and a
 * path can carry different types on different node types; both cases become the union
 * of members, so passing ANY valid member type-checks (a wrong-type-for-a-specific-node
 * still fails loud at bind — the honest best an instance-free SDK can do). `polymorphic`
 * lists the >1-member paths for the header note.
 */
export function collectTargets(manifest: ApiManifest): { targets: TargetInfo[]; polymorphic: string[] } {
  const byPath = new Map<string, Set<string>>();
  for (const node of Object.values(manifest.nodes)) {
    for (const [path, prop] of Object.entries(node.props)) {
      if (!prop.animatable || prop.target === undefined) continue;
      const set = byPath.get(path) ?? new Set<string>();
      for (const member of prop.type.split('|')) set.add(member.trim());
      byPath.set(path, set);
    }
  }
  const targets = [...byPath.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([path, set]) => ({ path, valueTypes: [...set].sort() }));
  const polymorphic = targets.filter((t) => t.valueTypes.length > 1).map((t) => `${t.path}: ${t.valueTypes.join(' | ')}`);
  return { targets, polymorphic };
}

const tsValueOf = (valueType: string): string => TS_VALUE_TYPE[valueType] ?? 'unknown';

/**
 * Generate the typed-SDK source (a `.ts` module). Emits a `KnownTrackPath` union, a
 * `TrackTarget` template (`` `${string}/${KnownTrackPath}` ``), per-path `TypeIdOf` /
 * `ValueOf` conditional maps, and a re-typed `track` re-export whose runtime IS
 * `@glissade/core`'s `track` (only the types are narrowed). Deterministic: paths are
 * sorted, so the same manifest → byte-identical output (drift-guardable with `--check`).
 */
export function generateTypedSdk(manifest: ApiManifest): string {
  const { targets, polymorphic } = collectTargets(manifest);
  const usedCoreTypes = [
    ...new Set(targets.flatMap((t) => t.valueTypes.map((v) => CORE_TYPE_IMPORTS[v])).filter((n): n is string => n !== undefined)),
  ].sort();
  /** union of value-type id literals for a target, e.g. `'color' | 'paint'`. */
  const typeIdUnion = (t: TargetInfo): string => t.valueTypes.map((v) => `'${v}'`).join(' | ');
  /** union of TS value types for a target, e.g. `string | Paint`. */
  const valueUnion = (t: TargetInfo): string => [...new Set(t.valueTypes.map(tsValueOf))].join(' | ');

  const L: string[] = [];
  L.push(`// GENERATED by \`gs types\` from the describe() API manifest v${manifest.version} — DO NOT EDIT.`);
  L.push('// Regenerate after a glissade upgrade (or when you add a defineComponent target):');
  L.push('//   gs types --out glissade-targets.ts');
  L.push('// Then import `track` from here instead of @glissade/core to type-check your targets.');
  if (polymorphic.length) L.push(`// Polymorphic paths (accept a value-type UNION): ${polymorphic.join(', ')}`);
  L.push('');
  L.push(`import { track as _track, type Track, type Key } from '@glissade/core';`);
  if (usedCoreTypes.length) L.push(`import type { ${usedCoreTypes.join(', ')} } from '@glissade/core';`);
  L.push('');

  L.push('/** Every animatable prop path in the describe() taxonomy — a typo\'d path is a type error. */');
  L.push(`export type KnownTrackPath =`);
  for (const t of targets) L.push(`  | '${t.path}'`);
  L.push(`  ;`);
  L.push('');
  L.push('/** A track target: any node id + a KNOWN animatable path. */');
  L.push('export type TrackTarget = `${string}/${KnownTrackPath}`;');
  L.push('');

  L.push('/** The value-type id each path expects (a wrong `type` arg is a type error;');
  L.push(' *  a polymorphic prop like `fill: color|paint` accepts either member). */');
  L.push('type TypeIdOf<P extends TrackTarget> =');
  for (const t of targets) L.push(`  P extends \`\${string}/${t.path}\` ? ${typeIdUnion(t)} :`);
  L.push('  never;');
  L.push('');
  L.push('/** The value each path animates (the keyframe value type). */');
  L.push('type ValueOf<P extends TrackTarget> =');
  for (const t of targets) L.push(`  P extends \`\${string}/${t.path}\` ? ${valueUnion(t)} :`);
  L.push('  never;');
  L.push('');

  L.push('/**');
  L.push(' * Type-checked `track` — only a KNOWN path + its correct value type compile.');
  L.push(' * Runtime is `@glissade/core`\'s `track` verbatim (only the types are narrowed).');
  L.push(' */');
  L.push('export const track = _track as <P extends TrackTarget>(');
  L.push('  target: P,');
  L.push('  type: TypeIdOf<P>,');
  L.push('  keys: Key<ValueOf<P>>[],');
  L.push('  opts?: { editable?: boolean },');
  L.push(') => Track<ValueOf<P>>;');
  L.push('');
  return L.join('\n');
}

// ─────────────────────────────────────────────────────────────────────────────
// `gs types --global` (0.47 "verifiable ground-truth") — the ambient window.glissade
// `.d.ts` generator. `gs types` (above) gave the ESM `track()` author typo→compile
// safety; the NO-BUILD `<script src>` + window.glissade author got NOTHING. This
// emits a SELF-CONTAINED ambient declaration (no `import`/`typeof import(...)`, since
// that author has no node_modules) typing the whole `window.glissade` surface from
// the manifest's `surface` section, so `window.glissade.Rect({…})` / `glissade
// .timeline(…)` type-check and a typo'd member is a compile error.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * value-type id → the SELF-CONTAINED TS type used in the ambient d.ts. Opaque core
 * types (`paint`/`fontAxes`/`path`) map to local `Gs*` aliases instead of the real
 * `@glissade/core` names, so the emitted file needs no imports (the no-build author
 * has no node_modules to resolve `Paint` from).
 */
const AMBIENT_VALUE_TYPE: Record<string, string> = {
  number: 'number',
  vec2: 'readonly [number, number]',
  'vec2-arc': 'readonly [number, number]',
  color: 'string',
  string: 'string',
  boolean: 'boolean',
  paint: 'GsPaint',
  fontAxes: 'GsFontAxes',
  path: 'GsPathValue',
};

/** The node constructors that get a real per-node props interface (form:'constructor'). */
const CONSTRUCTOR_NODES = new Set(['Group', 'Rect', 'Circle', 'Path', 'Text', 'Image', 'Video', 'Layout']);

/**
 * Map a manifest prop `type` string to a SELF-CONTAINED TS type for the ambient
 * d.ts. Precise for the known value-type ids (incl. a `|`-union of them, e.g.
 * `color|paint` → `string | GsPaint`); best-effort `unknown` for opaque construction
 * types (`SketchStyle`, `BlendMode`, the `anchor` preset union, …) whose real shapes
 * aren't self-containedly expressible — permissive, so authoring never fights it.
 */
function ambientPropType(manifestType: string): string {
  const members = manifestType.split('|').map((m) => m.trim());
  if (members.every((m) => m in AMBIENT_VALUE_TYPE)) {
    return [...new Set(members.map((m) => AMBIENT_VALUE_TYPE[m]!))].join(' | ');
  }
  if (manifestType === 'Node[]') return 'GsNode[]';
  return 'unknown';
}

/**
 * Derive a surface taxonomy when the manifest predates 0.47 (no `surface`): node
 * names that are known constructors → constructors, helpers + core callables →
 * functions, `easings` → object, plus the opaque type-only names. Keeps
 * `gs types --global --from <old-api.json>` working (best-effort).
 */
function surfaceOf(manifest: ApiManifest): SurfaceEntry[] {
  if (manifest.surface && manifest.surface.length > 0) return manifest.surface;
  const out: SurfaceEntry[] = [];
  for (const name of Object.keys(manifest.nodes)) {
    if (CONSTRUCTOR_NODES.has(name)) out.push({ name, kind: 'value', iife: true, form: 'constructor' });
    else out.push({ name, kind: 'value', iife: true, form: 'function' });
  }
  for (const h of manifest.helpers) out.push({ name: h.name, kind: 'value', iife: true, form: 'function' });
  for (const name of ['timeline', 'createScene', 'track', 'evaluate', 'stagger', 'describe']) out.push({ name, kind: 'value', iife: true, form: 'function' });
  out.push({ name: 'easings', kind: 'value', iife: true, form: 'object' });
  for (const name of ['Paint', 'PathValue', 'FontAxes']) out.push({ name, kind: 'type', iife: false, form: 'type' });
  const seen = new Set<string>();
  return out.filter((e) => (seen.has(e.name) ? false : (seen.add(e.name), true))).sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * Generate the SELF-CONTAINED ambient `window.glissade` `.d.ts` from the manifest's
 * `surface` taxonomy. Emits opaque `Gs*` aliases for the complex types, a real
 * per-node construction-props interface for each node constructor (value types
 * reused from the manifest), a best-effort signature per callable, and the global
 * augmentation (`declare global { interface Window { glissade }; const glissade }`).
 * Deterministic (everything sorted) + pure, so it's `--check`-gateable.
 *
 * HONEST about approximation: node instances / Paint / FontAxes / PathValue / the
 * timeline document are OPAQUE brands (the real shapes need the published types);
 * helper signatures beyond the headline authoring calls are `(...args) => any`.
 * The value it delivers is member-name + node-construction-prop type-checking — a
 * typo'd `window.glissade.Reet` or an unknown surface member is a compile error.
 */
export function generateAmbientDts(manifest: ApiManifest): string {
  const surface = surfaceOf(manifest);
  const byName = new Map(manifest.surface ? manifest.surface.map((e) => [e.name, e]) : []);
  const builderMethods = [...manifest.builder.methods.map((m) => m.name)].sort();

  const L: string[] = [];
  L.push(`// GENERATED by \`gs types --global\` from the describe() API manifest v${manifest.version} — DO NOT EDIT.`);
  L.push('// Self-contained ambient types for the NO-BUILD `window.glissade` IIFE (<script src>).');
  L.push('// Regenerate after a glissade upgrade:  gs types --global --out glissade.d.ts');
  L.push('// Reference it from your tsconfig `include` (or a /// <reference path> ) — no imports needed.');
  L.push('//');
  L.push('// APPROXIMATE: node instances, Paint, FontAxes, PathValue and the Timeline document are');
  L.push('// OPAQUE brands, and helper signatures beyond the headline authoring calls are `(...args) => any`.');
  L.push('// What IS checked: every surface member name + each node constructor\'s construction props.');
  L.push('');
  L.push('export {};');
  L.push('');

  // Opaque best-effort aliases for the complex/type-only names.
  L.push('/** Opaque best-effort types — the real shapes live in @glissade/core|scene. */');
  L.push('type GsPaint = string | { readonly [key: string]: unknown };');
  L.push('type GsFontAxes = { readonly [axis: string]: number };');
  L.push('type GsPathValue = readonly unknown[];');
  L.push("type GsNode = { readonly __glissadeNode: 'node' };");
  L.push("type GsScene = { readonly __glissadeScene: 'scene' };");
  L.push("type GsTimeline = { readonly __glissadeTimeline: 'timeline' };");
  L.push('');

  // The timeline builder — methods from describe().builder (chained, best-effort args).
  L.push('/** The `timeline(tl => …)` builder surface (methods from describe().builder). */');
  L.push('interface GsTimelineBuilder {');
  for (const name of builderMethods) L.push(`  ${name}(...args: any[]): GsTimelineBuilder;`);
  L.push('}');
  L.push('');

  // Per-node construction props (real types from the manifest).
  const ctorNodes = surface.filter((e) => e.form === 'constructor' && manifest.nodes[e.name]).map((e) => e.name).sort();
  const propsInterfaceName = (node: string): string => `Gs${node}Props`;
  for (const node of ctorNodes) {
    const props = manifest.nodes[node]!.props;
    L.push(`/** Construction props for \`new glissade.${node}({ … })\` (best-effort; opaque prop types → \`unknown\`). */`);
    L.push(`interface ${propsInterfaceName(node)} {`);
    for (const prop of Object.keys(props).sort()) {
      L.push(`  ${JSON.stringify(prop)}?: ${ambientPropType(props[prop]!.type)};`);
    }
    // Permissive index signature: the manifest doesn't enumerate EVERY construction
    // prop (e.g. Path.data), so accept unknown extras rather than red-line valid
    // authoring — the KNOWN props above still keep their real (checked) types.
    L.push('  [prop: string]: unknown;');
    L.push('}');
    L.push('');
  }

  // The window.glissade surface interface.
  L.push('/** Every `window.glissade.<name>` export (a typo\'d member is a compile error). */');
  L.push('interface GlissadeGlobal {');
  for (const e of surface) {
    if (e.kind !== 'value' || !e.iife) continue;
    L.push(`  ${JSON.stringify(e.name)}: ${ambientMemberType(e, ctorNodes)};`);
  }
  L.push('}');
  L.push('');

  // Global augmentation: window.glissade + the bare `glissade` global.
  L.push('declare global {');
  L.push('  interface Window {');
  L.push('    glissade: GlissadeGlobal;');
  L.push('  }');
  L.push('  const glissade: GlissadeGlobal;');
  L.push('}');
  L.push('');
  return L.join('\n');
}

/** The TS type for one window.glissade value member (constructor / function / object). */
function ambientMemberType(e: SurfaceEntry, ctorNodes: string[]): string {
  if (e.form === 'object') return 'Record<string, unknown>';
  if (e.form === 'constructor') {
    const props = ctorNodes.includes(e.name) ? `Gs${e.name}Props` : 'Record<string, unknown>';
    return `new (props?: ${props}) => GsNode`;
  }
  // form 'function' — real-ish signatures for the headline authoring calls, best-effort otherwise.
  switch (e.name) {
    case 'timeline':
      return '(build: (tl: GsTimelineBuilder) => void) => GsTimeline';
    case 'createScene':
      return '(spec: { size: { w: number; h: number }; children: GsNode[] }) => GsScene';
    case 'track':
      return '(target: string, type: string, keys: readonly unknown[], opts?: { editable?: boolean }) => unknown';
    default:
      return '(...args: any[]) => any';
  }
}
