/**
 * Golden scene: `each()` deterministic parametric instancing (0.13). A 3×3 grid
 * of Rects is generated by a single `each(9, ...)` call — the factory positions
 * each clone from its px-mapped `place`, and a fade+pop entrance clip is fanned
 * across them with `distribute: 'from-center'`, so the centre tile enters first
 * and the corners last. The generated `${id}/${i}` ids bind the staggered
 * tracks; the scene is pure data, byte-compared on Skia in CI.
 *
 * This pins the whole `each` contract end to end: id generation → scene
 * indexing → clip fan-out → the from-center stagger curve, all reconstructed
 * identically every evaluation (and every export shard). The entrance is the
 * stdlib `popIn` — now that popIn authors a VEC2 `scale` channel (the 0.13
 * canary fix), it binds correctly to the node's vec2 `scale` signal. The
 * emitted tracks are byte-identical to the prior inline `popInVec` workaround
 * (opacity 0→1 + scale [0.8,0.8]→[1,1] over 0.4s, easeOutCubic), so this golden
 * stays byte-stable.
 */

import { timeline } from '@glissade/core';
import { popIn } from '@glissade/core/clips';
import { each, Rect, createScene, type SceneModule } from '@glissade/scene';

const W = 640;
const H = 360;
const TILE = 96;

// The grid box is inset from the frame edges so the corner tiles sit fully
// in-frame; `box` maps each clone's aspect fraction into these px coordinates.
const BOX = { w: 460, h: 220, origin: [90, 70] as const };

// `each` is a pure build-time function, so calling it fresh per createScene()
// (the factory convention — every consumer gets a new graph) and once more for
// the timeline tracks both reconstruct the identical id set + tracks.
const buildGrid = (): ReturnType<typeof each> =>
  each(
    9,
    (_i, ctx) => {
      const [px, py] = ctx.place;
      // place is an aspect FRACTION; map it to px through the grid box (ctx
      // exposes the fraction, the result the px — author the mapping once).
      return new Rect({
        width: TILE,
        height: TILE,
        cornerRadius: 14,
        fill: '#9ef0c0',
        position: [BOX.origin[0] + px * BOX.w, BOX.origin[1] + py * BOX.h],
      });
    },
    {
      id: 'card',
      layout: { kind: 'grid', cols: 3 },
      motion: {
        clip: popIn({ duration: 0.4 }),
        startSec: 0.2,
        stagger: 0.18,
        distribute: 'from-center',
      },
    },
  );

const mod: SceneModule = {
  createScene: () =>
    createScene({
      size: { w: W, h: H },
      children: [
        new Rect({ id: 'bg', width: W, height: H, position: [W / 2, H / 2], fill: '#10131a' }),
        buildGrid().node,
      ],
    }),
  timeline: timeline({
    duration: 3,
    fps: 60,
    tracks: buildGrid().tracks,
  }),
};

export default mod;
